name:       sgf-xmonad
version:    '1.3.0'
synopsis:   sgf's xmonad config
category:   Graphics
author:     sgf
maintainer: sgf.dma@gmail.com
license:    BSD3
github:     sgf-dma/sgf-xmonad-config

dependencies:
- base
- tagged
- process
- filepath
- directory
- X11
- xmonad
- xmonad-contrib
- xmonad-entryhelper
- sgf-xmonad-modules
- sgf-haskell-common
- base
- tagged
- process
- filepath
- directory
- X11
- xmonad
- xmonad-contrib
- xmonad-entryhelper
- sgf-xmonad-modules
- sgf-haskell-common
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall

executables:
  xmonad:
    main: xmonad.hs
    source-dirs: src
  default-xmonad:
    main: default-xmonad.hs
    source-dirs: src
